### ISSUE TITLE
Plugin seems to stop working immediately after launch on foxy using navigation2 (main branch).

### ISSUE THREAD

**Issue by garyrightbot** [SteveMacenski/spatio_temporal_voxel_layer#181]
I'm running the navigation2 stack (main branch) with the STVL plugin with https://github.com/SteveMacenski/spatio_temporal_voxel_layer/pull/180 PR merged on my local STVL plugin source.

I'm using the RealSense D435i camera to get PointCloud2 data.

My configuration for the nav2_params.yaml file for the same are:

```
      stvl_layer:
        plugin: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"
        enabled: true
        voxel_decay: 1.0
        decay_model: 0
        voxel_size: 0.2
        track_unknown_space: true
        max_obstacle_height: 3.0
        unknown_threshold: 15
        mark_threshold: 0
        update_footprint_enabled: true
        combination_method: 1
        origin_z: 2.0
        publish_voxel_map: false
        transform_tolerance: 0.2
        mapping_mode: false
        map_save_duration: 10.0
        observation_sources: pointcloud
        pointcloud:
          data_type: PointCloud2
          topic: /camera/depth/color/points
          marking: true
          clearing: true
          obstacle_range: 4.5
          min_obstacle_height: 0.0
          max_obstacle_height: 3.0
          expected_update_rate: 0.0
          observation_persistence: 0.0
          inf_is_valid: false
          voxel_filter: false
          clear_after_reading: true
          max_z: 3.0
          min_z: 0.1
          vertical_fov_angle: 0.8745
          horizontal_fov_angle: 1.048
          decay_acceleration: 1.0
          model_type: 0
```

What I observe is that: As soon as I set the initial pose, the costmap has inputs from the STVL plugin and detects obstacles in front of the camera and keeps them on the costmap until the decay period is over. It does not detect any obstacle after that - it  seems as if the plugin stops working right after its first input to the costmap.

Could this be because of incorrect config params? Or is it due to the inter-distribution compatibility issues between nav2 main and STVL main (or foxy-devel since both branches are in sync at this time) as pointed out by @SteveMacenski on https://github.com/SteveMacenski/spatio_temporal_voxel_layer/issues/179 or is it due to the changes in https://github.com/SteveMacenski/spatio_temporal_voxel_layer/pull/180 ?
