### ISSUE TITLE
Obstacles are cleared from the voxel layer but not from the local costmap

### ISSUE THREAD

**Issue by siferati** [SteveMacenski/spatio_temporal_voxel_layer#199]
Edit: forgot to mention, I'm using ros melodic. STVL was installed by `sudo apt-get install ros-melodic-spatio-temporal-voxel-layer`

Hello, I'm having a problem where the obstacles are cleared from the voxel layer but not from the local costmap. **However, this only affects the local costmap, the global costmap works fine!**

You can see [here](https://streamable.com/ulgjql) a short clip I recorded of it happening. The green lines you see once I give it a new nav goal are from the [costmap_converter](http://wiki.ros.org/costmap_converter), proof that the local costmap was indeed not cleared and it's not just a visual bug.

Below are my costmap params:

```yaml
# common_costmap.yaml

robot_base_frame: base_footprint
footprint: [[-0.7, -0.55], [0.7, -0.55], [0.7, 0.55], [-0.7, 0.55]]
publish_frequency: 30

rgdb_obstacles:
  enabled:                  true
  voxel_decay:              30
  decay_model:              0
  voxel_size:               0.05
  track_unknown_space:      true
  max_obstacle_height:      3.0
  unknown_threshold:        15
  mark_threshold:           0
  update_footprint_enabled: true
  combination_method:       1
  obstacle_range:           8.5
  origin_z:                 0.0
  publish_voxel_map:        true
  observation_sources:      realsense_mark realsense_clear

  realsense_mark:
    data_type: PointCloud2
    topic: realsense/depth/points
    marking: true
    clearing: false
    min_obstacle_height: 0.01
    max_obstacle_height: 3.0
    voxel_filter: true
    
  realsense_clear:
    data_type: PointCloud2
    topic: realsense/depth/points
    marking: false
    clearing: true
    min_z: 0.01
    max_z: 9.0
    vertical_fov_angle: 0.96
    horizontal_fov_angle: 1.22
    decay_acceleration: 5
    model_type: 0
```

```yaml
# global_costmap.yaml

global_costmap:
  plugins:
    - {name: map, type: 'costmap_2d::StaticLayer'}
    - {name: rgdb_obstacles, type: 'spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer'}
    - {name: inflation, type: 'costmap_2d::InflationLayer'}

  map:
    subscribe_to_updates: true

  inflation:
    inflation_radius: 1
    cost_scaling_factor: 5
```

```yaml
# local_costmap.yaml

local_costmap:
  plugins:
    - {name: rgdb_obstacles, type: 'spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer'}

  rolling_window: true
  width: 6
  height: 6
  resolution: 0.05
```
